[build]
publish = "public" # default hugo build folder
command = "hugo --gc --minify --enableGitInfo" # --themesDir ../.."  hugo build command

[context.production.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"